# Generated by Django 5.0.6 on 2024-10-21 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('freelancer_id', models.UUIDField()),
                ('user_image', models.ImageField(null=True, upload_to='user_images/')),
                ('id_image', models.ImageField(null=True, upload_to='id_images/')),
                ('id_type', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
